### ISSUE TITLE
Introduce shared weekday/weekend schedules 

### ISSUE THREAD

**Issue by zero-udo** [zero-udo/eurotronic-cometblue#2]
Introduce methods for schedules shared for all weekdays (Mo-Fr) or weekends (Sa-So)

**Comment by giddyhup** [comment]
Module const is not found when executing the example code: 

```
python3 bin/cometbluetest.py
Traceback (most recent call last):
  File "bin/cometbluetest.py", line 1, in <module>
    from cometblue import CometBlue, Weekday
  File "/usr/local/lib/python3.7/dist-packages/cometblue/__init__.py", line 10, in <module>
    import const
ModuleNotFoundError: No module named 'const'
```

The actual file is here: 
```
ls /usr/local/lib/python3.7/dist-packages/cometblue/
const.py  __init__.py  __pycache__
```
