### ISSUE TITLE
Module const is not found when executing the example code

### ISSUE THREAD

**Issue by zero-udo** [zero-udo/eurotronic-cometblue#3]
Module const is not found when executing the example code: 

```
python3 bin/cometbluetest.py
Traceback (most recent call last):
  File "bin/cometbluetest.py", line 1, in <module>
    from cometblue import CometBlue, Weekday
  File "/usr/local/lib/python3.7/dist-packages/cometblue/__init__.py", line 10, in <module>
    import const
ModuleNotFoundError: No module named 'const'
```

The actual file is here: 
```
ls /usr/local/lib/python3.7/dist-packages/cometblue/
const.py  __init__.py  __pycache__
```

_Originally posted by @giddyhup in https://github.com/zero-udo/eurotronic-cometblue/issues/2#issuecomment-1010707556_

**Comment by zero-udo** [comment]
@giddyhup thanks for bringing this to my attention.
CometBlueTests.py is running the unit test when called from the command line, also the import of the constants was fixed.
A new release 1.0.2 is published on pypi and you should be able to update via `pip`
